/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.sql.*;
import Model.DatabaseConnection;
import java.text.Format;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author KESTROY
 */
public class addNewDonor extends javax.swing.JFrame {

    /**
     * Creates new form addNewDonor
     */
    public addNewDonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fullnameTF = new javax.swing.JTextField();
        fathernameTF = new javax.swing.JTextField();
        mothernameTF = new javax.swing.JTextField();
        mobileNoTF = new javax.swing.JTextField();
        dobTF = new com.toedter.calendar.JDateChooser();
        genderTF = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cityTF = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        CityTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTF = new javax.swing.JTextArea();
        bloodgroupTF = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        saveBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        donoridTF = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Add New Donor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 700, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("New Donor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 126, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 126, 15, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Full Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Father Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mother Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 242, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date of Birth");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mobile No");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 318, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 359, -1, -1));

        fullnameTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fullnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameTFActionPerformed(evt);
            }
        });
        getContentPane().add(fullnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 157, 159, -1));

        fathernameTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(fathernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 198, 159, -1));

        mothernameTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(mothernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 159, -1));

        mobileNoTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(mobileNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 162, -1));
        getContentPane().add(dobTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 280, 162, -1));

        genderTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderTF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(genderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 359, 162, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 178, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Blood Group");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 216, -1, -1));

        cityTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cityTF.setText("City");
        getContentPane().add(cityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 257, -1, -1));

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Address.setText("Address");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 295, -1, -1));

        emailTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 175, 162, -1));

        CityTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(CityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 254, 162, -1));

        addressTF.setColumns(20);
        addressTF.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        addressTF.setRows(5);
        jScrollPane1.setViewportView(addressTF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 295, -1, -1));

        bloodgroupTF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bloodgroupTF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        getContentPane().add(bloodgroupTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 216, 162, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 427, 700, -1));

        saveBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });
        getContentPane().add(saveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 447, -1, -1));

        resetBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update details.png"))); // NOI18N
        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });
        getContentPane().add(resetBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 447, -1, -1));

        closeBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit application.png"))); // NOI18N
        closeBTN.setText("Close");
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });
        getContentPane().add(closeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 447, -1, -1));

        donoridTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        donoridTF.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(donoridTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select max(donorId) from donor");
            if(rs.first())
            {
                int id=rs.getInt(1);
                id=id+1;
                String str=String.valueOf(id);
                donoridTF.setText(str);    
            }
            else
                donoridTF.setText("1");
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void fullnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameTFActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeBTNActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addNewDonor().setVisible(true);
    }//GEN-LAST:event_resetBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        String donorid=donoridTF.getText();
        String name=fullnameTF.getText();
        String fathername=fathernameTF.getText();
        String mothername=mothernameTF.getText();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        String DOB=dFormat.format(dobTF.getDate());
        String mobileNo=mobileNoTF.getText();
        String gender=(String)genderTF.getSelectedItem();
        String email=emailTF.getText();
        String bloodgroup=(String)bloodgroupTF.getSelectedItem();
        String city=CityTF.getText();
        String address=addressTF.getText();
        
        try{
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("Insert Into donor values('"+donorid+"','"+name+"','"+fathername+"','"+mothername+"','"+DOB+"','"+mobileNo+"','"+gender+"','"+email+"','"+bloodgroup+"','"+city+"','"+address+"')");
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            new addNewDonor().setVisible(true);
        }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
        
        
        
    }//GEN-LAST:event_saveBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField CityTF;
    private javax.swing.JTextArea addressTF;
    private javax.swing.JComboBox<String> bloodgroupTF;
    private javax.swing.JLabel cityTF;
    private javax.swing.JButton closeBTN;
    private com.toedter.calendar.JDateChooser dobTF;
    private javax.swing.JLabel donoridTF;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField fathernameTF;
    private javax.swing.JTextField fullnameTF;
    private javax.swing.JComboBox<String> genderTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mobileNoTF;
    private javax.swing.JTextField mothernameTF;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton saveBTN;
    // End of variables declaration//GEN-END:variables
}
